language: python
python:
  - 2.7.13
  - 3.4
  - 3.7
  # PyPy versions
  - pypy   # PyPy2 5.8
  - pypy3  # Pypy3 5.8
matrix:
  include:
    - python: 2.7
      env: JYTHON=org.python:jython-installer:2.7.1

    
before_install:
# Use the Jython standalone - 2.7.1 (supported)
  - export JYTHON_URL='http://search.maven.org/remotecontent?filepath=org/python/jython-standalone/2.7.1/jython-standalone-2.7.1.jar'
  - if [ -n "$JYTHON" ]; then wget $JYTHON_URL -O jython.jar; fi

# Use the Ubuntu Xenial's Repository version of Jython - 2.5.3 (non supported)
#   - if [ -n "$JYTHON" ]; then sudo apt-get install jython; fi

before_script: if [ -n "$JYTHON" ]; then export PYTHON_EXE="java -jar jython.jar "; "$PYTHON_EXE" -c "print ''"; else export PYTHON_EXE=python; fi; echo "Using-> '$PYTHON_EXE'"

install:
#  - pip install -r requirements.txt

# command to run tests
script: $PYTHON_EXE -m unittest test



branches:
  only:
    - tests

# after_success:
#   - codecov # submit coverage
