language: python
python:
  - 2.6
  - 2.7.13
  - 3.4
  - 3.7
  # PyPy versions
  - pypy   # PyPy2 5.8
  - pypy3  # Pypy3 5.8
matrix:
  exclude:
    - python: 2.6
      env: JYTHON=true
# command to install dependencies


before_install: if [ "$JYTHON" == "true" ]; then sudo apt-get install jython; fi

before_script: if [ "$JYTHON" == "true" ]; then export PYTHON_EXE=jython; jython -c "print ''"; else export PYTHON_EXE=python; fi


install:
#  - pip install -r requirements.txt

# command to run tests
script: $PYTHON_EXE -m unittest test



branches:
  only:
    - tests

# after_success:
#   - codecov # submit coverage
